################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
build/app_trace \
build/app_trace/gcov \
build/app_update \
build/asio/asio/asio/src \
build/bootloader/bootloader_support/src \
build/bootloader/log \
build/bootloader/main \
build/bootloader/micro-ecc/micro-ecc \
build/bootloader/soc/esp32 \
build/bootloader/soc/src \
build/bootloader/spi_flash \
build/bootloader_support/src \
build/bt \
build/coap/libcoap/src \
build/coap/port \
build/console/argtable3 \
build/console \
build/console/linenoise \
build/cxx \
build/driver \
build/esp-tls \
build/esp32 \
build/esp32/hwcrypto \
build/esp_adc_cal \
build/esp_event \
build/esp_http_client \
build/esp_http_client/lib \
build/esp_http_server/src \
build/esp_http_server/src/util \
build/esp_https_ota/src \
build/esp_https_server/src \
build/esp_ringbuf \
build/ethernet \
build/ethernet/eth_phy \
build/expat/expat/expat/lib \
build/fatfs/src \
build/freemodbus/modbus/ascii \
build/freemodbus/modbus/functions \
build/freemodbus/modbus \
build/freemodbus/modbus/rtu \
build/freemodbus/modbus_controller \
build/freemodbus/port \
build/freertos \
build/heap \
build/jsmn/src \
build/json/cJSON \
build/lib \
build/libsodium/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_auth \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha256 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
build/libsodium/libsodium/src/libsodium/crypto_box \
build/libsodium/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_core/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_core/hchacha20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
build/libsodium/libsodium/src/libsodium/crypto_core/salsa/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash \
build/libsodium/libsodium/src/libsodium/crypto_hash \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha256 \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha512 \
build/libsodium/libsodium/src/libsodium/crypto_kdf/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_kdf \
build/libsodium/libsodium/src/libsodium/crypto_kx \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/argon2 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
build/libsodium/libsodium/src/libsodium/crypto_secretbox \
build/libsodium/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_shorthash \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24 \
build/libsodium/libsodium/src/libsodium/crypto_sign \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519 \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20 \
build/libsodium/libsodium/src/libsodium/crypto_stream \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20 \
build/libsodium/libsodium/src/libsodium/crypto_stream/xsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_verify/sodium \
build/libsodium/libsodium/src/libsodium/randombytes \
build/libsodium/libsodium/src/libsodium/sodium \
build/libsodium/port/crypto_hash_mbedtls \
build/libsodium/port \
build/log \
build/lwip/apps/dhcpserver \
build/lwip/apps/ping \
build/lwip/lwip/src/api \
build/lwip/lwip/src/apps/sntp \
build/lwip/lwip/src/core \
build/lwip/lwip/src/core/ipv4 \
build/lwip/lwip/src/core/ipv6 \
build/lwip/lwip/src/netif \
build/lwip/port/esp32/debug \
build/lwip/port/esp32/freertos \
build/lwip/port/esp32/netif \
build/lwip/port/esp32 \
build/main \
build/main/component/Adafruit_GFX \
build/main/components/Adafruit_GFX \
build/main/components/Barometer \
build/main/components/Blinker \
build/main/components/DHThumidity \
build/main/components/MLX90393 \
build/main/components/counter \
build/main/components/i2c \
build/main/components/mQttClient \
build/mbedtls/mbedtls/library \
build/mbedtls/port \
build/mdns \
build/micro-ecc/micro-ecc \
build/mqtt/esp-mqtt/lib \
build/mqtt/esp-mqtt \
build/newlib \
build/nghttp/nghttp2/lib \
build/nghttp/port \
build/nvs_flash/src \
build/openssl/library \
build/openssl/platform \
build/protobuf-c/protobuf-c/protobuf-c \
build/protocomm/proto-c \
build/protocomm/src/common \
build/protocomm/src/security \
build/protocomm/src/transports \
build/pthread \
build/sdmmc \
build/smartconfig_ack \
build/soc/esp32 \
build/soc/src \
build/spi_flash \
build/spiffs \
build/spiffs/spiffs/src \
build/tcp_transport \
build/tcpip_adapter \
build/ulp \
build/unity/unity/src \
build/unity \
build/vfs \
build/wear_levelling \
build/wifi_provisioning/proto-c \
build/wifi_provisioning/src \
build/wpa_supplicant/port \
build/wpa_supplicant/src/crypto \
build/wpa_supplicant/src/fast_crypto \
build/wpa_supplicant/src/wpa2/eap_peer \
build/wpa_supplicant/src/wpa2/tls \
build/wpa_supplicant/src/wpa2/utils \
build/wpa_supplicant/src/wps \
build/xtensa-debug-module \
main \
main/components/Adafruit_GFX \
main/components/Adafruit_GFX/fontconvert \
main/components/Barometer \
main/components/Blinker \
main/components/DHThumidity \
main/components/GeneralUtils \
main/components/MLX90393 \
main/components/NVS \
main/components/SSD1306 \
main/components/UpdateFirmware \
main/components/WiFi \
main/components/counter \
main/components/i2c \
main/components/mQttClient \
main/components/sntp \
main/ulp \

